language: cpp
jobs:
  include:
    - name: Ubuntu Linux
      os: linux
      dist: focal
      before_script:
        - apt-get install -y cppcheck
      after_script:
        - cppcheck -q --enable=warning,performance,portability,style --error-exitcode=1 .
    - name: macOS
      os: osx
      osx_image: xcode12
    - name: Windows Server
      os: windows
script:
  - cmake -S . -B build
  - cmake --build build
  - cd build
  - ctest
notifications:
  email: false
