sudo: false

language: cpp

jobs:
  include:
    - stage: test
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - lcov
            - cppcheck
      install:
        - cd ${TRAVIS_BUILD_DIR}
        - gem install coveralls-lcov
      before-script:
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --zerocounters
      scripts:
        - cd ${TRAVIS_BUILD_DIR}
        - cppcheck --quiet --enable=warning,performance,portability,style --error-exitcode=1 .
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_CXX_FLAGS="-Wall -Werror -g -O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
        - cmake --build .
        - ctest
      after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --capture --output-file coverage.info
        - lcov -r coverage.info '/usr/**' ${TRAVIS_BUILD_DIR}'/build/**' ${TRAVIS_BUILD_DIR}'/tests/**' -o coverage.info
        - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
    - stage: test
      os: osx
      osx_image: xcode12u
      install:
        - cd ${TRAVIS_BUILD_DIR}
        - export CC=clang
        - export CXX=clang++
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - ctest

notifications:
  email: false
