language: cpp
os:
  - linux
  - osx
  - windows
dist: focal
osx_image: xcode12
before_script:
  if: os = linux
  - apt-get install -y cppcheck
script:
  - cmake -S . -B build
  - cmake --build build
  - cd build
  - ctest
after_script:
  if: os = linux
  - cppcheck -q --enable=warning,performance,portability,style --error-exitcode=1 .
notifications:
  email: false
