language: cpp
os:
  - linux
  - osx
  - windows
jobs:
  include:
    - os: linux
      dist: focal
      before_script:
        - apt-get install -y cppcheck
      after_script:
        - cppcheck -q --enable=warning,performance,portability,style --error-exitcode=1 .
    - os: osx
      osx_image: xcode12
    - os: windows2
script:
  - cmake -S . -B build
  - cmake --build build
  - cd build
  - ctest
notifications:
  email: false
