language: cpp
jobs:
  include:
    - name: Ubuntu Linux (Focal 20.04)
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - cppcheck
      after_script:
        - cd ..
        - cppcheck -q -I include -i build -i examples --enable=all --suppress=missingIncludeSystem --error-exitcode=1 . 
    - name: macOS (10.15.5)
      os: osx
      osx_image: xcode12
    - name: Windows Server (1809)
      os: windows
script: ./scripts/run-test.sh
notifications:
  email: false
